### ISSUE TITLE
Ainda funciona?

### ISSUE THREAD

**Issue by FabioZumbi12** [luizwbr/PagSeguro-VirtueMart-3#2]
Olá

Baixei e configurei tudo certinho com o token e tals, mas parece que não retornou o pedido aprovado pra minha loja.

No pagseguro colokei essa url:

http://areaz12server.net.br//index.php?option=com_virtuemart&view=pluginresponse&task=pluginnotification

E ta assim no pedido feito: http://prntscr.com/c0zx5x

O primeiro é do pedido pendente e a segunda linha é do pedido aprovado, mas no meu virtuemart continua pendente :(

Fiz tudo certo?

**Comment by luizwbr** [comment]
Olá Fábio.
Está marcada a configuração para usar a nova API do PagSeguro?

**Comment by FabioZumbi12** [comment]
Olá,

Onde tem esta opção? Não a encontrei no modulo no VM. Pode me indicar onde ela esta por favor?

Obrigado.

**Comment by luizwbr** [comment]
Sim, está na configuração do PagSeguro ( Preferências > Integrações ):
![config_pagseguro](https://cloud.githubusercontent.com/assets/308603/17376890/f13ba0d6-598d-11e6-821e-0900ce321785.png)

**Comment by FabioZumbi12** [comment]
Ah sim, estão habilitados e colei o link ali mesmo!
Mas tem uma mensagem dizendo ali que vai ser descontinuado. O modulo ja esta atualizado pra funcionar de outra forma?

**Comment by luizwbr** [comment]
Na verdade o plugin já está usando a nova forma de notificação, porém apenas a criação da transação no PagSeguro que está sendo feita usando o método antigo.

O mais estranho é que hoje mesmo verifiquei uma notificação com este plugin no meu site constantando que está funcionando.

Será que não teria algum tipo de bloqueio no teu servidor ou algum outro plugin bloqueando a execução dele?

Se tiver o plugin do Mercado Pago, experimenta desativar ele. Na verdade tenta deixar somente o plugin de pagamento do PagSeguro para verificar se a notificação ocorre normalmente.

**Comment by FabioZumbi12** [comment]
É, ainda não funcionou!

Voce poderia adicionar uma opção para usarmos a SandBox do pagseguro para testarmos as configurações?

Um botão do tipo radio para alternar entre sandbox e produção ja daria certo. Vo testar fazer isso e se eu conseguir eu crio um fork do seu projeto e abro um pull request (mas se vc puder faezr tbm, seria bom ^^)

Aqui o sandbox: https://sandbox.pagseguro.uol.com.br/

Obrigado.

**Comment by FabioZumbi12** [comment]
Adicionei o modo sandbox no código, testei na minha loja e funciona perfeitamente ^^

https://github.com/luizwbr/PagSeguro-VirtueMart-3/pull/3
https://github.com/luizwbr/PagSeguro-VirtueMart-3/pull/4

Agora posso testar o feedback do pagseguro mais facilmente :)
Abraços!

**Edit:**
Que estranho cara, o plugin do PayPal retorna tudo certinho mas do pagseguro não. O que será?

**Comment by luizwbr** [comment]
Legal Fabio, obrigado, já adicionei ao master.

Pois é, o jeito seria fazer um debug do retorno da notificação. O arquivo de log foi gerado com as transações?

**Comment by FabioZumbi12** [comment]
Então Luiz, não encontrei o Log do seu modulo, só do VirtueMart em ./logs mas não tem nada lá do pagseguro.

Até vi que vc usa "logs.info()" (algo assim) mas não achei mesmo.
Obrigado.

**Comment by luizwbr** [comment]
@FabioZumbi12, e no link Log que fica no VirtueMart, apareceu algo? 
![log_virtuemart](https://cloud.githubusercontent.com/assets/308603/17610200/ec5977de-6011-11e6-9c32-249294882ac7.png)

**Comment by luizvin** [comment]
Olá. Também tive o mesmo problema com um cliente, adicionei o link no pagseguro mas o status não é atualizado automaticamente. É um recurso muito interessante já que o cliente na mesma hora tem o status confirmado do pagamento que ele através do pagseguro. Uma dúvida que pode parecer boba é... o link deve ter uma ou duas barras?

http://www.meusite.com.br//index.php?option=com_virtuemart&view=pluginresponse&task=pluginnotification
ou
http://www.meusite.com.br/index.php?option=com_virtuemart&view=pluginresponse&task=pluginnotification

E a dúvida principal... por que não está funcionando? No meu caso também já verifiquei que no pagseguro a url está habilitada, e o pagamento via formulário html também.

Agradeço desde já por qualquer ajuda que puderem me dar.

**Comment by FabioZumbi12** [comment]
O meu ainda não funciona mas como não tenho muito fluxo estou atualizando manualmente, tbm tenho outras formas de pagamento.

Ainda aguardo uma solução. Se conseguir arrumar agradeço se compartilhar ^^

**Comment by raphaelfogaca** [comment]
Olá senhores, boa noite! Luiz valeu pelo plugin.

Configurei tudo conforme documentação e já fiz testes em sandbox funcionando ok.
Mas não sei como configurar um retorno para mudar o status do pedido automaticamente, alguem pode me ajudar?

Obrigado

**Comment by luizwbr** [comment]
@raphaelfogaca, foi detalhado logo acima como inserir a url de notificação.

**Comment by pgdigital** [comment]
Alguem conseguiu resolver aqui o problema do status pessoal ? Estou com mesmo problema.

**Comment by luizwbr** [comment]
Estou migrando para este aqui, que é um fork do oficial do Pagseguro. https://github.com/luizwbr/virtuemart

**Comment by pgdigital** [comment]
muito obrigado Luiz, nao esta pronto ainda nao ne?


________________________________
[http://www.pgdigital.net/images/stories/logo-email2015.png]

PG DIGITAL :: Soluções em Webmarketing
Claudeir Ribeiro - Consultor de Projetos e Neg. Digitais
Cel: (45) 9928-8144 Tim // Whatsapp (45) 8825-0003
Facebook: pgdigitalfoz
Twitter: pgdigital
Conheça portfólio completo - Visualizar
WWW.PGDGIGITAL.NET<http://www.pgdigital.net/portfolio-clientes.html>
www.joomlacessorios.com.br
        - Loja virtual, Sites Institucionais,
  Sites para Imobiliarias e Hotsites
- Atualizações e manutenção de sites
- Atendimento On Line para sites
- Hospedagem e Registro de Domínios
- E-Mail Marketing Digital, Google, Sites de Busca

Uma empresa sempre em busca soluções para seus clientes !

**Comment by luizwbr** [comment]
É pra estar, mas passei pro Pagseguro pra ver se inserem no repositório oficial.
