### ISSUE TITLE
Problema com a Taxa do Meio de pagamento e Produto

### ISSUE THREAD

**Issue by shoust123** [luizwbr/PagSeguro-VirtueMart-3#5]
Caro Weber,
O Plugin apresenta o seguinte erro, caso o produto tenha algum imposto ou o meio de pagamento do PagSeguro seja atribuido alguma taxa, essa taxa / imposto não é repassada para o PagSeguro quando o cliente e redirecionado, apenas o valor normal sem taxa e imposto.

Poderia corrigir o problema?

**Comment by luizwbr** [comment]
Estou migrando para outro módulo, para usar o oficial do PagSeguro.
