### ISSUE TITLE
erro pagseguro

### ISSUE THREAD

**Issue by dbbrito** [luizwbr/PagSeguro-VirtueMart-3#6]
Olá Luiz, implantei o virtuemart mas quando finalizo o pagseguro me retorna o erro abaix:
[HTTP 400] - BAD_REQUEST [11030] - Item amount out of range: 0.00

Sabe por favor me informar que erro é esse?
Muito obrigado

**Comment by leolopesbraga** [comment]
Estou tendo o mesmo erro relatado na hora de fechar a compra.

**Comment by dbbrito** [comment]
não consegui descobrir até hoje, o desenvolvedor não responde....uma pena

2017-11-13 16:01 GMT-02:00 leolopesbraga <notifications@github.com>:

**Comment by luizwbr** [comment]
Caros, este módulo acabou sendo depreciado por não ser muito antigo e não utilizar todos os recursos do Pagseguro. 

Foi feito um fork do original do PagSeguro que é compatível com VM 3: https://github.com/luizwbr/virtuemart
